export const subjects = [
    "မြန်မာစာ",
    "Myanmar",
    "English",
    "Mathematics",
    "ပထဝီဝင်",
    "သမိုင်းစာ",
    "သိပ္ပံဘာသာ",
    "လူမှုရေးဘာသာ",
    "Chemistry",
    "Physics",
    "Biology",
    "Economic",
    "STEM 1",
    "STEM 2",
    "STEM 3",
    "စာရိတ္တနှင့်ပြည်သူ့နီတိ",
];
